/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import java.util.Date;
/**
 *
 * @author AC Tech
 */
public class billing extends javax.swing.JFrame {

    /**
     * Creates new form billing
     */
    public int finalTotal;
    public billing() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        datee = new javax.swing.JLabel();
        timee = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        idprod = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        nameprod = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rateprod = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        my_table = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        totale = new javax.swing.JTextField();
        amountpaid = new javax.swing.JTextField();
        amountreturn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoice = new javax.swing.JTextArea();
        status = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/billing-machine.png"))); // NOI18N
        jLabel1.setText("Billing");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 7, 340, 147));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1385, 57, -1, -1));

        datee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(datee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1531, 57, -1, -1));

        timee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(timee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1539, 107, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Temps:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1385, 107, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 167, 1688, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Details Client");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 195, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Nom");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 254, -1, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 247, 243, 32));

        telephone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });
        getContentPane().add(telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 247, 194, 32));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Telephone");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 254, -1, -1));

        email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(832, 255, 243, 32));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 262, -1, -1));

        address.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(1225, 247, 243, 32));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Adresse");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1129, 254, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 305, 1678, 10));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Produit ID");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 387, -1, -1));

        idprod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idprodActionPerformed(evt);
            }
        });
        getContentPane().add(idprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 380, 125, 32));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Details Produit");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 328, -1, -1));

        nameprod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameprodActionPerformed(evt);
            }
        });
        getContentPane().add(nameprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 380, 194, 32));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Nom Produit");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 387, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Prix unitaire");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(643, 387, -1, -1));

        rateprod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rateprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateprodActionPerformed(evt);
            }
        });
        getContentPane().add(rateprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 380, 243, 32));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Description");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 390, -1, -1));

        description.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 380, 243, 32));

        quantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1128, 380, 131, 32));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Quantite");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1027, 387, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add3.png"))); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 420, 150, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 478, 1689, 10));

        my_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom produit", "Prix unitaire", "Quantite", "Description"
            }
        ));
        jScrollPane1.setViewportView(my_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 495, 360, 310));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Detail Calcul");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 495, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Montant payé:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Montant à rendre:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Total:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(741, 542, -1, -1));
        getContentPane().add(totale, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 536, 347, 31));

        amountpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpaidActionPerformed(evt);
            }
        });
        getContentPane().add(amountpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 347, 31));
        getContentPane().add(amountreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 630, 347, 31));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/enregister.png"))); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 520, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/external-reload.png"))); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 600, 149, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-sign.png"))); // NOI18N
        jButton4.setText("Fermer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 600, 149, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/imprimer.png"))); // NOI18N
        jButton5.setText("Imprimer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 520, 150, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add3.png"))); // NOI18N
        jButton6.setText("Facture");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 650, 150, -1));

        invoice.setColumns(20);
        invoice.setRows(5);
        jScrollPane2.setViewportView(invoice);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 340, 340));

        status.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAYE", "NON PAYE", " " }));
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, 240, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 700, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new billing().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
        String n = name.getText();
        ResultSet res = connection.db_Mysql.interrogerBD("select * from customer where name like'"+n+"%'");
        try {
            if(res.next()){
                name.setText(res.getString(1));
                telephone.setText(res.getString(2));
                email.setText(res.getString(3));
                address.setText(res.getString(4));
            }else{
                telephone.setText("");
                email.setText("");
                address.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
        String tel = telephone.getText();
        ResultSet res = connection.db_Mysql.interrogerBD("select * from customer where telephone like'"+tel+"%'");
        try {
            if(res.next()){
                name.setText(res.getString(1));
                telephone.setText(res.getString(2));
                email.setText(res.getString(3));
                address.setText(res.getString(4));
            }else{
                name.setText("");
                email.setText("");
                address.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_telephoneActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
        String m = email.getText();
        ResultSet res = connection.db_Mysql.interrogerBD("select * from customer where email like'"+m+"%'");
        try {
            if(res.next()){
                name.setText(res.getString(1));
                telephone.setText(res.getString(2));
                email.setText(res.getString(3));
                address.setText(res.getString(4));
            }else{
                name.setText("");
                telephone.setText("");
                address.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_emailActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
        String add = address.getText();
        ResultSet res = connection.db_Mysql.interrogerBD("select * from customer where address like'"+add+"%'");
        try {
            if(res.next()){
                name.setText(res.getString(1));
                telephone.setText(res.getString(2));
                email.setText(res.getString(3));
                address.setText(res.getString(4));
            }else{
                name.setText("");
                telephone.setText("");
                email.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_addressActionPerformed

    private void idprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idprodActionPerformed
        // TODO add your handling code here:
        String idpro = idprod.getText();
        ResultSet res = connection.db_Mysql.interrogerBD("select * from product where idproduct like'"+idpro+"%'");
        try {
            if(res.next()){
                idprod.setText(res.getString(1));
                nameprod.setText(res.getString(2));
                rateprod.setText(res.getString(3));
                quantity.setText("1");
                description.setText(res.getString(4));
            }else{
                nameprod.setText("");
                rateprod.setText("");
                description.setText("");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_idprodActionPerformed

    private void nameprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameprodActionPerformed

    private void rateprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rateprodActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int prix = Integer.parseInt(rateprod.getText());
        int quantite = Integer.parseInt(quantity.getText());
        int total = prix * quantite;
        DefaultTableModel model = (DefaultTableModel)my_table.getModel();
        model.addRow(new Object[] {nameprod.getText(),prix+"FBU",quantite,description.getText()});
        finalTotal = finalTotal+total;
        String finalTotal1 = String.valueOf(finalTotal);
        totale.setText(finalTotal1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amountpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpaidActionPerformed
        // TODO add your handling code here:
        String paidAmount = amountpaid.getText();
        int p = Integer.parseInt(paidAmount);
        finalTotal = p-finalTotal;
        String finalTotal1 = String.valueOf(finalTotal);
        amountreturn.setText(finalTotal1);
        amountreturn.setEditable(false);
        
        
    }//GEN-LAST:event_amountpaidActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            invoice.print();
        }catch(java.awt.print.PrinterException e){
	JOptionPane.showMessageDialog(null, e);
}
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //==============================================================
        int refs = 1325 + (int) (Math.random()*4238);

        //==============================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
           
        
      invoice.append("Ambaza Marcellin Company: \n"+
              "Reference:\t\t"+ refs +
              "\n======================================\n"+
                    "\t Details du client \n"+
              "\t ---------------------------\n"+
              "Nom :\t\t" + name.getText() + "\n"+
              "Telephone No :\t\t"+ telephone.getText() + "\n"+
              "adresse : \t\t"+ address.getText() + "\n"+
              "\n========================================\n"+
                    "\t Details du produit \n"+
              "\t ---------------------------\n"+
              "Nom produit: \t\t"+ nameprod.getText() + "\n"+
              "Prix unitaire: \t\t"+ rateprod.getText() + "FBU\n"+
              "Quantite : \t\t"+ quantity.getText() + "\n"+
              "\n=========================================\n"+
              "Total : \t\t"+ totale.getText() + "FBU\n"+
              "Montant payé : \t\t"+ amountpaid.getText() + "FBU\n"+
              "Montant à rendre : \t"+ amountreturn.getText() + "FBU\n"+
              "Status : \t\t"+ status.getSelectedItem() + "\n"+
              "===========================================\n"+
              "\nDate : "+Tdate.format(timer.getTime()) +
              "\tTemps : "+ tTime.format(timer.getTime()) +
              "\n\n\n \t Merci "+name.getText()
      );
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        
        
        String nomclient = name.getText();
        String telclient = telephone.getText();
        String addclient = address.getText();
        String nomprod = nameprod.getText();
        String prix = rateprod.getText();
        String quantite = quantity.getText();
        String total = totale.getText();
        String stat = (String)status.getSelectedItem();
        //String date
        
            if(connection.db_Mysql.updateBD("insert into report(namecustomer,telephone,address,nameproduct,rate,quantite,total,date,status) values('"+nomclient+"','"+telclient+"','"+addclient+"','"+nomprod+"','"+prix+"','"+quantite+"','"+total+"','"+Tdate.format(timer.getTime())+"','"+stat+"')")>0){
                JOptionPane.showMessageDialog(null, "Enregistrement avec succes");
            }else
            {
                JOptionPane.showMessageDialog(null, "Erreur d'enregistrement");
            }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField amountpaid;
    private javax.swing.JTextField amountreturn;
    private javax.swing.JLabel datee;
    private javax.swing.JTextField description;
    private javax.swing.JTextField email;
    private javax.swing.JTextField idprod;
    private javax.swing.JTextArea invoice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable my_table;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nameprod;
    private javax.swing.JTextField quantity;
    private javax.swing.JTextField rateprod;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField telephone;
    private javax.swing.JLabel timee;
    private javax.swing.JTextField totale;
    // End of variables declaration//GEN-END:variables
}
