/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.JOptionPane;

/**
 *
 * @author AC Tech
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public int z = 0 ;
    public home() {
        initComponents();
        this.setLocationRelativeTo(null);
        addCustomerbtn.setVisible(false);
        detailCustomerbtn.setVisible(false);
        editCustomerbtn.setVisible(false);
        deleteCustomerbtn.setVisible(false);
        newProductbtn.setVisible(false);
        editProductbtn.setVisible(false);
        deleteProductbtn.setVisible(false);
        detailProductbtn.setVisible(false);
        billingbtn.setVisible(false);
        logoutbtn.setVisible(false);
        closeAppbtn.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustomerbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        editCustomerbtn = new javax.swing.JButton();
        deleteCustomerbtn = new javax.swing.JButton();
        detailCustomerbtn = new javax.swing.JButton();
        newProductbtn = new javax.swing.JButton();
        deleteProductbtn = new javax.swing.JButton();
        editProductbtn = new javax.swing.JButton();
        detailProductbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        billingbtn = new javax.swing.JButton();
        closeAppbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        report = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 776));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addCustomerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        addCustomerbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addCustomerbtnComponentShown(evt);
            }
        });
        addCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show-hide.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        editCustomerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/change-user-male.png"))); // NOI18N
        editCustomerbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                editCustomerbtnComponentShown(evt);
            }
        });
        editCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(editCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        deleteCustomerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-male-user_2.png"))); // NOI18N
        deleteCustomerbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deleteCustomerbtnComponentShown(evt);
            }
        });
        deleteCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCustomerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        detailCustomerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/details-pane (1).png"))); // NOI18N
        detailCustomerbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                detailCustomerbtnComponentShown(evt);
            }
        });
        detailCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailCustomerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(detailCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        newProductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-product.png"))); // NOI18N
        newProductbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                newProductbtnComponentShown(evt);
            }
        });
        newProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProductbtnActionPerformed(evt);
            }
        });
        getContentPane().add(newProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        deleteProductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        deleteProductbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                deleteProductbtnComponentShown(evt);
            }
        });
        deleteProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductbtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 10, -1, -1));

        editProductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-prod.png"))); // NOI18N
        editProductbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                editProductbtnComponentShown(evt);
            }
        });
        editProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProductbtnActionPerformed(evt);
            }
        });
        getContentPane().add(editProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        detailProductbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/details-pane.png"))); // NOI18N
        detailProductbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                detailProductbtnComponentShown(evt);
            }
        });
        detailProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailProductbtnActionPerformed(evt);
            }
        });
        getContentPane().add(detailProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout2.png"))); // NOI18N
        logoutbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutbtnComponentShown(evt);
            }
        });
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1420, 10, -1, -1));

        billingbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/billing-machine_1.png"))); // NOI18N
        billingbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billingbtnComponentShown(evt);
            }
        });
        billingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingbtnActionPerformed(evt);
            }
        });
        getContentPane().add(billingbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, -1, -1));

        closeAppbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        closeAppbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                closeAppbtnComponentShown(evt);
            }
        });
        closeAppbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAppbtnActionPerformed(evt);
            }
        });
        getContentPane().add(closeAppbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nouveau client");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Details client");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Editer client");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Supprimer client");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Nouveau produit");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Editer produit");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Details produit");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Supprimer produit");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Facture");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Se deconnecter");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Fermer");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 130, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/img.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 270, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cash-receipt.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 250, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/billing-machine.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 260, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/img.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cash-receipt.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/billing-machine.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("RAPPORT");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, -1, -1));

        report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/billing.png"))); // NOI18N
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });
        getContentPane().add(report, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-contacts_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("DETTES");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "voulez vous vraiment se deconnecter?","Selected",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void closeAppbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAppbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "voulez vous vraiment Fermer l'Application?","Selected",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeAppbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        if(z==0){
            try{
                Thread.sleep(250);
                addCustomerbtn.setVisible(true);
                jLabel1.setVisible(true);
            }catch(Exception e){
                
            }
        }else{
        addCustomerbtn.setVisible(false);
        detailCustomerbtn.setVisible(false);
        editCustomerbtn.setVisible(false);
        deleteCustomerbtn.setVisible(false);
        newProductbtn.setVisible(false);
        editProductbtn.setVisible(false);
        deleteProductbtn.setVisible(false);
        detailProductbtn.setVisible(false);
        billingbtn.setVisible(false);
        logoutbtn.setVisible(false);
        closeAppbtn.setVisible(false);
        jLabel1.setVisible(false);
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel9.setVisible(false);
        jLabel10.setVisible(false);
        jLabel11.setVisible(false);
        z=0;
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void addCustomerbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addCustomerbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                detailCustomerbtn.setVisible(true);
                jLabel2.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_addCustomerbtnComponentShown

    private void detailCustomerbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_detailCustomerbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                editCustomerbtn.setVisible(true);
                jLabel3.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_detailCustomerbtnComponentShown

    private void editCustomerbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_editCustomerbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                deleteCustomerbtn.setVisible(true);
                jLabel4.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_editCustomerbtnComponentShown

    private void deleteCustomerbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteCustomerbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                newProductbtn.setVisible(true);
                jLabel5.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_deleteCustomerbtnComponentShown

    private void newProductbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_newProductbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                editProductbtn.setVisible(true);
                jLabel6.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_newProductbtnComponentShown

    private void editProductbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_editProductbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                detailProductbtn.setVisible(true);
                jLabel7.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_editProductbtnComponentShown

    private void detailProductbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_detailProductbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                deleteProductbtn.setVisible(true);
                jLabel8.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_detailProductbtnComponentShown

    private void deleteProductbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_deleteProductbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                billingbtn.setVisible(true);
                jLabel9.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_deleteProductbtnComponentShown

    private void billingbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billingbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                logoutbtn.setVisible(true);
                jLabel10.setVisible(true);
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_billingbtnComponentShown

    private void logoutbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutbtnComponentShown
        // TODO add your handling code here:
        try{
                Thread.sleep(250);
                closeAppbtn.setVisible(true);
                jLabel11.setVisible(true);
                z=1;
            }catch(Exception e){
                
            }
    }//GEN-LAST:event_logoutbtnComponentShown

    private void closeAppbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_closeAppbtnComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_closeAppbtnComponentShown

    private void addCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerbtnActionPerformed
        // TODO add your handling code here:
        new newCustomer().setVisible(true);
    }//GEN-LAST:event_addCustomerbtnActionPerformed

    private void editCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerbtnActionPerformed
        // TODO add your handling code here:
        new updateCustomer().setVisible(true);
    }//GEN-LAST:event_editCustomerbtnActionPerformed

    private void detailCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailCustomerbtnActionPerformed
        // TODO add your handling code here:
        new detailCustomer().setVisible(true);
    }//GEN-LAST:event_detailCustomerbtnActionPerformed

    private void deleteCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCustomerbtnActionPerformed
        // TODO add your handling code here:
        new deleteCustomer().setVisible(true);
    }//GEN-LAST:event_deleteCustomerbtnActionPerformed

    private void newProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProductbtnActionPerformed
        // TODO add your handling code here:
        new newProduct().setVisible(true);
    }//GEN-LAST:event_newProductbtnActionPerformed

    private void editProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProductbtnActionPerformed
        // TODO add your handling code here:
        new updateProduct().setVisible(true);
    }//GEN-LAST:event_editProductbtnActionPerformed

    private void deleteProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductbtnActionPerformed
        // TODO add your handling code here:
        new deleteProduct().setVisible(true);
    }//GEN-LAST:event_deleteProductbtnActionPerformed

    private void detailProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailProductbtnActionPerformed
        // TODO add your handling code here:
        new detailProduit().setVisible(true);
    }//GEN-LAST:event_detailProductbtnActionPerformed

    private void billingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingbtnActionPerformed
        // TODO add your handling code here:
        new billing().setVisible(true);
    }//GEN-LAST:event_billingbtnActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        new report().setVisible(true);
    }//GEN-LAST:event_reportActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new dettes().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerbtn;
    private javax.swing.JButton billingbtn;
    private javax.swing.JButton closeAppbtn;
    private javax.swing.JButton deleteCustomerbtn;
    private javax.swing.JButton deleteProductbtn;
    private javax.swing.JButton detailCustomerbtn;
    private javax.swing.JButton detailProductbtn;
    private javax.swing.JButton editCustomerbtn;
    private javax.swing.JButton editProductbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton newProductbtn;
    private javax.swing.JButton report;
    // End of variables declaration//GEN-END:variables
}
